import {
  cafeComLeite,
  Americano,
  Arabe,
  CafeGelado,
  Capuccino,
  ChocolateQuente,
  Cubano,
  ExpressoCremoso,
  Expresso,
  Havaiano,
  Irlandes,
  Latte,
  Macchiato,
  Mochaccino,
} from "@/assets/coffes";

export const coffeArray = [
  {
    id: 1,
    img: Expresso,
    title: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    attributes: ["Tradicional"],
    price: 990,
  },
  {
    id: 2,
    img: Americano,
    attributes: ["Tradicional"],
    title: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 990,
  },
  {
    id: 2,
    img: ExpressoCremoso,
    attributes: ["Tradicional"],
    title: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 990,
  },
  {
    id: 2,
    img: CafeGelado,
    attributes: ["Tradicional", "gelado"],
    title: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 990,
  },
  {
    id: 2,
    img: cafeComLeite,
    attributes: ["Tradicional", "com leite"],
    title: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 990,
  },
  {
    id: 2,
    img: Latte,
    attributes: ["Tradicional", "com leite"],
    title: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 990,
  },
  {
    id: 2,
    img: Capuccino,
    attributes: ["Tradicional", "com leite"],
    title: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 990,
  },
  {
    id: 2,
    img: Macchiato,
    attributes: ["Tradicional", "com leite"],
    title: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 990,
  },
  {
    id: 2,
    img: Mochaccino,
    attributes: ["Tradicional", "com leite"],
    title: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 990,
  },
  {
    id: 2,
    img: ChocolateQuente,
    attributes: ["especial", "com leite"],
    title: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 990,
  },
  {
    id: 2,
    img: Cubano,
    attributes: ["especial", "alcoólico", "gelado"],
    title: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 990,
  },
  {
    id: 2,
    img: Havaiano,
    attributes: ["especial"],
    title: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 990,
  },
  {
    id: 2,
    img: Arabe,
    attributes: ["especial"],
    title: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 990,
  },
  {
    id: 2,
    img: Irlandes,
    attributes: ["especial", "alcoólico"],
    title: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 990,
  },
];
